name = "youtube-playlist-explorer-cache"
main = "src/index.js"
compatibility_date = "2026-03-23"

kv_namespaces = [
  { binding = "CACHE_STORE", id = "9904336b52284b39a928a9b6b8cc7c14" }
]

[vars]
ALLOWED_ORIGINS = "https://fabiosilverio.github.io,http://127.0.0.1:4173,http://localhost:4173"
